version: "3.9"

services:
  react-frontend:
    build: ./frontend
    ports:
      - "5175:5175"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host", "--port", "5175"]

  express-backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
